
package vista;

public class FormularioRegistro extends javax.swing.JDialog {

    /**
     * Creates new form FormularioRegistro
     */
    public FormularioRegistro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Registro");
        btnGrupo.add(aradioCliente);
        btnGrupo.add(aradioEmpleado);
        cjboxHabilidades.addItem("Lavado y planchado");
        cjboxHabilidades.addItem("Limpieza");
        cjboxHabilidades.addItem("Cocina");
        for(int i=0;i<33;i++){
                bbjPanel1.getComponent(i).setVisible(false);
        }
        setSize(500, 100);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrupo = new javax.swing.ButtonGroup();
        alblSeleccioneRol = new javax.swing.JLabel();
        aradioCliente = new javax.swing.JRadioButton();
        aradioEmpleado = new javax.swing.JRadioButton();
        abtnAceptar = new javax.swing.JButton();
        bbjPanel1 = new javax.swing.JPanel();
        btxtNombre = new javax.swing.JTextField();
        blblNombre = new javax.swing.JLabel();
        blblApellido = new javax.swing.JLabel();
        btxtApellido = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        blblFechaNacimiento = new javax.swing.JLabel();
        btxtTelefono = new javax.swing.JTextField();
        bjDateChooser1 = new com.toedter.calendar.JDateChooser();
        blblSexo = new javax.swing.JLabel();
        bradioMasculino = new javax.swing.JRadioButton();
        bradioFemenino = new javax.swing.JRadioButton();
        blblCorreoElectronico = new javax.swing.JLabel();
        btxtCorreo = new javax.swing.JTextField();
        blblContraseña = new javax.swing.JLabel();
        btxtPassword = new javax.swing.JPasswordField();
        blblContraseña2 = new javax.swing.JLabel();
        btxtPassword2 = new javax.swing.JPasswordField();
        clblCedula = new javax.swing.JLabel();
        ctxtCedula = new javax.swing.JTextField();
        clblNombreUsuario = new javax.swing.JLabel();
        ctxtNombreUsuario = new javax.swing.JTextField();
        cjLabel2 = new javax.swing.JLabel();
        txtOtroTelefono = new javax.swing.JTextField();
        cjLabel3 = new javax.swing.JLabel();
        cjboxHabilidades = new javax.swing.JComboBox<>();
        cjLabel1 = new javax.swing.JLabel();
        clblCallePrincipal = new javax.swing.JLabel();
        ctxtCallePrincipal = new javax.swing.JTextField();
        clblCalleSecundaria = new javax.swing.JLabel();
        ctxtCalleSecundaria = new javax.swing.JTextField();
        clblNumeracion = new javax.swing.JLabel();
        ctxtNumeracion = new javax.swing.JTextField();
        btnTerminarRegistro = new javax.swing.JButton();

        setTitle("Registro");

        alblSeleccioneRol.setText("Seleccione su rol: ");
        alblSeleccioneRol.setAutoscrolls(true);

        aradioCliente.setText("Cliente");
        aradioCliente.setAutoscrolls(true);

        aradioEmpleado.setText("Empleado");
        aradioEmpleado.setToolTipText("");
        aradioEmpleado.setAutoscrolls(true);

        abtnAceptar.setText("Aceptar");
        abtnAceptar.setAutoscrolls(true);
        abtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abtnAceptarActionPerformed(evt);
            }
        });

        bbjPanel1.setAutoscrolls(true);

        blblNombre.setText("Nombre: ");

        blblApellido.setText("Apellido:");

        lblTelefono.setText("Teléfono:");

        blblFechaNacimiento.setText("Fecha de nacimiento:");

        blblSexo.setText("Sexo");

        bradioMasculino.setText("Masculino");

        bradioFemenino.setText("Femenino");

        blblCorreoElectronico.setText("Correo electrónico: ");

        blblContraseña.setText("Ingrese su contraseña:");

        btxtPassword.setToolTipText("Mínimo 8 caracteres ");

        blblContraseña2.setText("Ingrese de nuevo:");

        clblCedula.setText("Cédula:");

        clblNombreUsuario.setText("Nombre de usuario: ");

        cjLabel2.setText("Otro número de contacto: ");

        cjLabel3.setText("Habilidades que ofertas: ");

        cjLabel1.setText("Información de domicilio");

        clblCallePrincipal.setText("Calle Principal: ");

        clblCalleSecundaria.setText("Calle Secundaria:");

        clblNumeracion.setText("Numeración:");

        btnTerminarRegistro.setText("Terminar Registro");

        javax.swing.GroupLayout bbjPanel1Layout = new javax.swing.GroupLayout(bbjPanel1);
        bbjPanel1.setLayout(bbjPanel1Layout);
        bbjPanel1Layout.setHorizontalGroup(
            bbjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bbjPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(bbjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bbjPanel1Layout.createSequentialGroup()
                        .addGroup(bbjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cjLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(bbjPanel1Layout.createSequentialGroup()
                                .addGroup(bbjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cjLabel3)
                                    .addComponent(clblNombreUsuario))
                                .addGroup(bbjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bbjPanel1Layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(cjboxHabilidades, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(bbjPanel1Layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addGroup(bbjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ctxtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(bbjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(ctxtNombreUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                                                .addComponent(txtOtroTelefono, javax.swing.GroupLayout.Alignment.TRAILING)))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addGroup(bbjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clblNumeracion)
                            .addComponent(clblCalleSecundaria)
                            .addComponent(clblCallePrincipal, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(bbjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ctxtCallePrincipal)
                            .addComponent(ctxtNumeracion, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ctxtCalleSecundaria, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))
                    .addGroup(bbjPanel1Layout.createSequentialGroup()
                        .addGroup(bbjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clblCedula)
                            .addGroup(bbjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(bbjPanel1Layout.createSequentialGroup()
                                    .addComponent(blblFechaNacimiento)
                                    .addGap(18, 18, 18)
                                    .addComponent(bjDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))
                                .addGroup(bbjPanel1Layout.createSequentialGroup()
                                    .addGroup(bbjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(blblNombre)
                                        .addComponent(blblApellido)
                                        .addComponent(lblTelefono))
                                    .addGap(33, 33, 33)
                                    .addGroup(bbjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(btxtApellido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                                        .addComponent(btxtNombre, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btxtTelefono))))
                            .addGroup(bbjPanel1Layout.createSequentialGroup()
                                .addComponent(blblSexo)
                                .addGap(56, 56, 56)
                                .addComponent(bradioMasculino)
                                .addGap(18, 18, 18)
                                .addComponent(bradioFemenino))
                            .addGroup(bbjPanel1Layout.createSequentialGroup()
                                .addGroup(bbjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(blblContraseña)
                                    .addComponent(blblCorreoElectronico)
                                    .addComponent(blblContraseña2))
                                .addGap(45, 45, 45)
                                .addGroup(bbjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btxtCorreo)
                                    .addComponent(btxtPassword)
                                    .addComponent(btxtPassword2, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))))
                        .addGap(0, 416, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bbjPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cjLabel1)
                .addGap(113, 113, 113))
            .addGroup(bbjPanel1Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(btnTerminarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bbjPanel1Layout.setVerticalGroup(
            bbjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bbjPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(bbjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(blblNombre)
                    .addComponent(btxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bbjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(blblApellido)
                    .addComponent(btxtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bbjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefono)
                    .addComponent(btxtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bbjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(blblFechaNacimiento)
                    .addComponent(bjDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bbjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(blblSexo)
                    .addComponent(bradioMasculino)
                    .addComponent(bradioFemenino))
                .addGap(24, 24, 24)
                .addGroup(bbjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(blblCorreoElectronico)
                    .addComponent(btxtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bbjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(blblContraseña)
                    .addComponent(btxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bbjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(blblContraseña2)
                    .addComponent(btxtPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(bbjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bbjPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(cjLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addGroup(bbjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clblCedula)
                            .addComponent(ctxtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(bbjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clblNombreUsuario)
                            .addComponent(ctxtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(bbjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtOtroTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cjLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bbjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cjboxHabilidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cjLabel3)))
                    .addGroup(bbjPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(bbjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clblCallePrincipal)
                            .addComponent(ctxtCallePrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(bbjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clblCalleSecundaria)
                            .addComponent(ctxtCalleSecundaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(bbjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clblNumeracion)
                            .addComponent(ctxtNumeracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(58, 58, 58)
                .addComponent(btnTerminarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(328, 328, 328))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(alblSeleccioneRol)
                .addGap(18, 18, 18)
                .addComponent(aradioCliente)
                .addGap(18, 18, 18)
                .addComponent(aradioEmpleado)
                .addGap(40, 40, 40)
                .addComponent(abtnAceptar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(bbjPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alblSeleccioneRol)
                    .addComponent(aradioCliente)
                    .addComponent(aradioEmpleado)
                    .addComponent(abtnAceptar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bbjPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 752, Short.MAX_VALUE)
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abtnAceptarActionPerformed
        // TODO add your handling code here:
        if(aradioCliente.isSelected()){
            setSize(500, 700);
            setLocationRelativeTo(null);
            cjLabel1.setVisible(false);
            cjLabel2.setVisible(false);
            cjLabel3.setVisible(false);
            txtOtroTelefono.setVisible(false);
            cjboxHabilidades.setVisible(false);
            cjboxHabilidades.setVisible(false);
            clblCallePrincipal.setVisible(false);
            clblCalleSecundaria.setVisible(false);
            clblCedula.setVisible(false);
            clblNombreUsuario.setVisible(false);
            clblNumeracion.setVisible(false);
            ctxtCallePrincipal.setVisible(false);
            ctxtCalleSecundaria.setVisible(false);
            ctxtCedula.setVisible(false);
            ctxtNombreUsuario.setVisible(false);
            ctxtNumeracion.setVisible(false);
            bjDateChooser1.setVisible(true);
            blblApellido.setVisible(true);
            blblContraseña.setVisible(true);
            blblContraseña2.setVisible(true);
            blblCorreoElectronico.setVisible(true);
            blblFechaNacimiento.setVisible(true);
            blblNombre.setVisible(true);
            blblSexo.setVisible(true);
            bradioFemenino.setVisible(true);
            bradioMasculino.setVisible(true);
            btxtApellido.setVisible(true);
            btxtCorreo.setVisible(true);
            btxtNombre.setVisible(true);
            btxtPassword.setVisible(true);
            btxtPassword2.setVisible(true);
            btxtTelefono.setVisible(true);
            btnTerminarRegistro.setVisible(true);
            
            
        }else{
            setSize(860, 700);
            setLocationRelativeTo(null);
            for(int i=0;i<33;i++){
                bbjPanel1.getComponent(i).setVisible(true);
            }
        }
    }//GEN-LAST:event_abtnAceptarActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FormularioRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FormularioRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FormularioRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FormularioRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                FormularioRegistro dialog = new FormularioRegistro(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton abtnAceptar;
    private javax.swing.JLabel alblSeleccioneRol;
    public javax.swing.JRadioButton aradioCliente;
    public javax.swing.JRadioButton aradioEmpleado;
    public javax.swing.JPanel bbjPanel1;
    public com.toedter.calendar.JDateChooser bjDateChooser1;
    public javax.swing.JLabel blblApellido;
    public javax.swing.JLabel blblContraseña;
    public javax.swing.JLabel blblContraseña2;
    public javax.swing.JLabel blblCorreoElectronico;
    public javax.swing.JLabel blblFechaNacimiento;
    public javax.swing.JLabel blblNombre;
    public javax.swing.JLabel blblSexo;
    public javax.swing.JRadioButton bradioFemenino;
    public javax.swing.JRadioButton bradioMasculino;
    public javax.swing.ButtonGroup btnGrupo;
    public javax.swing.JButton btnTerminarRegistro;
    public javax.swing.JTextField btxtApellido;
    public javax.swing.JTextField btxtCorreo;
    public javax.swing.JTextField btxtNombre;
    public javax.swing.JPasswordField btxtPassword;
    public javax.swing.JPasswordField btxtPassword2;
    public javax.swing.JTextField btxtTelefono;
    public javax.swing.JLabel cjLabel1;
    public javax.swing.JLabel cjLabel2;
    public javax.swing.JLabel cjLabel3;
    public javax.swing.JComboBox<String> cjboxHabilidades;
    public javax.swing.JLabel clblCallePrincipal;
    public javax.swing.JLabel clblCalleSecundaria;
    public javax.swing.JLabel clblCedula;
    public javax.swing.JLabel clblNombreUsuario;
    public javax.swing.JLabel clblNumeracion;
    public javax.swing.JTextField ctxtCallePrincipal;
    public javax.swing.JTextField ctxtCalleSecundaria;
    public javax.swing.JTextField ctxtCedula;
    public javax.swing.JTextField ctxtNombreUsuario;
    public javax.swing.JTextField ctxtNumeracion;
    public javax.swing.JLabel lblTelefono;
    public javax.swing.JTextField txtOtroTelefono;
    // End of variables declaration//GEN-END:variables
}
